apiVersion: apps/v1
kind: Deployment
metadata:
   name: deploy-demo
   namespace: default
spec:
   replicas: 5
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: app-demo
              image: node-app
              imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
   name: node-app-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001
